#!/usr/bin/env osascript -l JavaScript

function bootstrap(session, command, split) {
  if (command instanceof Array) {
    let sessions = [session]
    for (let i = 1; i < command.length; i++) {
      sessions.push(session[`${split}WithSameProfile`]())
    }
    split =
      split === "splitVertically" ? "splitHorizontally" : "splitVertically"
    for (let i = 0; i < command.length; i++) {
      bootstrap(sessions[i], command[i], split)
    }
  } else if (command.length) {
    session.write({ text: command })
  }
}

function main(config) {
  const terminal = Application("iTerm")
  terminal.includeStandardAdditions = true

  const window = terminal.currentWindow()
  let tabs = [window.currentTab()]

  for (let i = 0; i < config.tabs.length; i++) {
    if (i !== 0) {
      tabs.push(window.createTabWithDefaultProfile())
    }
    let { commands, firstSplit } = config.tabs[i]
    if (!firstSplit) {
      firstSplit = "splitHorizontally"
    }
    bootstrap(tabs[i].currentSession(), commands, firstSplit)
  }

  tabs[0].select()
}

function run(argv) {
  const fileContents = $.NSString.stringWithContentsOfFile(argv[0]).js || "[]"
  const config = JSON.parse(fileContents)

  main(config)
}
