#!/usr/bin/env sh

echo 'Creating empty config...'
echo

tee ./.iterm-workspace <<-JSON
{
  "tabs": [
    {
      "commands": [
        ["# top left pane", "# top right pane"]
        "# bottom pane"
      ]
    } 
  ]
}
JSON

echo
echo 'Done! Now edit the .iterm-workspace config file in this directory to your liking.'
echo 'For a tutorial, see https://github.com/knrz/iterm-workspace'
