#!/usr/bin/env sh

echo 'Creating empty config...'
echo

tee ./.iterm-workspace <<-JSON
{
    "firstSplit": "splitVertically",
    "commands": []
}
JSON

echo
echo 'Done! Now edit the .iterm-workspace config file in this directory to your liking.'
echo 'For usage details, see https://github.com/knrz/iterm-workspace'