#!/usr/bin/env sh

config="$PWD/.iterm-workspace"

if [ -f $config ]; then
  bootstrap-iterm-workspace $config
else
  echo "No config found at $config..."
  echo 'Creating empty config...'
  echo

  tee ./.iterm-workspace <<-JSON
{
  "tabs": [
    {
      "commands": [
        ["# top left pane", "# top right pane"],
        "# bottom pane"
      ]
    }
  ]
}
JSON

  echo
  echo 'Done! Edit the .iterm-workspace config file in this directory to your liking.'
  echo 'To Get Started, see https://github.com/knrz/iterm-workspace'
fi
