#!/usr/bin/env sh

config="$PWD/${1:-".iterm-workspace"}"

if [ -f $config ]; then
  bootstrap-iterm-workspace $config
else
  echo "No config found at $config..."
  echo 'Creating empty config...'
  echo

  tee $config <<-JSON
{
  "tabs": [
    {
      "cd": "cd /path/to/directory",
      "commands": [
        ["# run in top left pane", "# run in top right pane"],
        "# run in bottom pane"
      ]
    }
  ]
}
JSON

  echo
  echo 'Done! Edit the .iterm-workspace config file in this directory to your liking.'
  echo 'To Get Started, see https://github.com/knrz/iterm-workspace'
fi
